<li>
              <div class="news_date">[field:pubdate function="MyDate('m/d',@me)"/]<span>[field:pubdate function="MyDate('Y',@me)"/]</span></div>
              <div class="news_t"><a href="[field:arcurl/]">[field:title/]</a></div>
              <div class="news">[field:description function='cn_substr(@me,30)'/]</div>
              <div class="news_info">[field:info/]...
                <p><a href="[field:arcurl/]">了解更多...</a></p>
              </div>
              <div class="clear"></div>
            </li>