<?php
$z[0]=Array("field","",149,168);
$z[0][4]['name']="title";
$z[1]=Array("global","",169,195);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",236,258);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",298,349);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",884,919);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1074,1103);
$z[5][4]['name']="position";
$z[6]=Array("type","<a class=\"gray\" href=\"[field:typelink/]\"><<返回</a>",1372,1448);
$z[7]=Array("field","",1470,1488);
$z[7][4]['name']="body";
$z[8]=Array("include","",1619,1656);
$z[8][4]['filename']="footer.htm";

?>