<?php
$z[0]=Array("field","",149,168);
$z[0][4]['name']="title";
$z[1]=Array("global","",169,195);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",236,265);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",305,363);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",898,933);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1089,1118);
$z[5][4]['name']="position";
$z[6]=Array("list","\r\n          <tr>\r\n            <td>◆ <a href=\"[field:arcurl/]\">[field:title/]</a></td>\r\n            <td>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</td>\r\n          </tr>\r\n          ",1533,1756);
$z[6][4]['pagesize']="20";
$z[7]=Array("include","",1898,1935);
$z[7][4]['filename']="footer.htm";

?>